export const ADD_TODO = 'ADD_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const DO_TODO = 'DO_TODO'
export const SET_TODOS = 'SET_TODOS'
export const TOGGLE_IS_LOADING = 'TOGGLE_IS_LOADING'
export const CHANGE_FILTER = 'CHANGE_FILTER'
